### ISSUE TITLE
[Feature Request] Add more unified syntax between ExcelIO and Exceljs

### ISSUE THREAD

**Issue by Freymaurer** [fslaborg/FsSpreadsheet#79]
Currently the main entrypoint for Exceljs io operations looks like this: 

```js
Xlsx.toFile("test.isa.investigation.xlsx", fswb)
```

So when we show code examples in ARCtrl, we have different syntax for js and f#, as we do not have this Xlsx type in ExcelIO. Might be nice to offer the same entrypoint in .NET, so docs can be applied better to both languages.

**Comment by Freymaurer** [comment]
This should be solved now @HLWeil ?

**Comment by HLWeil** [comment]
Yes
