### ISSUE TITLE
[Feature Request] Offer index-less generic json for spreadsheets

### ISSUE THREAD

**Issue by Freymaurer** [fslaborg/FsSpreadsheet#95]
We want to create a xlsx-diff funtionality based on generic json. For the tool to better understand insertions it would be preferrable to have no indices 🙂

**Comment by Freymaurer** [comment]
Required for: https://github.com/nfdi4plants/ARCitect/issues/198

**Comment by HLWeil** [comment]
And update docs for json parsing.
